spring.application.name=restful

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:mydb

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}

#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=10

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.highlight_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#logging.level.org.hibernate.orm.jdbc.bind=TRACE