-- Initial member: username vacationer / password password
INSERT INTO members (username, password, name, email)
VALUES (
    'vacationer',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    '여행자',
    'vacationer@example.com'
);

INSERT INTO articles (title, content, created_at, author_id)
SELECT item.title, item.content, DATE_SUB(NOW(), INTERVAL item.days_ago DAY), member.id
FROM members member
CROSS JOIN (
    SELECT 0 AS days_ago, '방학 첫날의 계획' AS title, '이번 방학에는 충분히 쉬면서 가까운 곳을 여행하려고 합니다.' AS content
    UNION ALL SELECT 1, '제주 바다 산책', '맑은 날 제주 바다를 따라 천천히 걸었습니다.'
    UNION ALL SELECT 2, '기차 여행 준비물', '간단한 간식과 책 한 권을 챙기니 기차 여행이 편했습니다.'
    UNION ALL SELECT 3, '여름 방학 독서', '방학 오후에는 시원한 카페에서 여행 에세이를 읽고 있습니다.'
    UNION ALL SELECT 4, '부산 해운대 아침', '사람이 적은 이른 아침 해운대 풍경이 좋았습니다.'
    UNION ALL SELECT 5, '방학 중 자전거 여행', '강변 자전거 길을 따라 한 시간 정도 달렸습니다.'
    UNION ALL SELECT 6, '강릉 커피 거리', '바다를 보며 마신 따뜻한 커피가 기억에 남습니다.'
    UNION ALL SELECT 7, '주말 여행 예산', '교통과 숙소를 미리 예약하니 예산을 아낄 수 있었습니다.'
    UNION ALL SELECT 8, '방학 아침 운동', '여행 전 체력을 기르려고 매일 가볍게 걷고 있습니다.'
    UNION ALL SELECT 9, '경주 한옥 숙소', '조용한 한옥에서 보낸 밤이 편안했습니다.'
    UNION ALL SELECT 10, '방학의 작은 목표', '하루에 새로운 장소 한 곳을 찾아보는 목표를 세웠습니다.'
    UNION ALL SELECT 11, '전주 비빔밥 여행', '전주 시장에서 먹은 비빔밥이 든든했습니다.'
    UNION ALL SELECT 12, '여행 사진 정리', '방학 동안 찍은 사진을 날짜별로 정리했습니다.'
    UNION ALL SELECT 13, '서울 야경 산책', '한강 주변을 걸으며 서울의 야경을 보았습니다.'
    UNION ALL SELECT 14, '방학 영화 추천', '여행을 떠나기 전 가벼운 로드무비를 봤습니다.'
    UNION ALL SELECT 15, '속초 시장 구경', '시장 골목을 돌며 따뜻한 간식을 먹었습니다.'
    UNION ALL SELECT 16, '혼자 떠난 당일치기', '혼자여도 원하는 속도로 여행할 수 있어 좋았습니다.'
    UNION ALL SELECT 17, '방학 점심 메뉴', '여행지에서 먹고 싶은 음식을 목록으로 만들었습니다.'
    UNION ALL SELECT 18, '남해 바람', '남해의 잔잔한 바다와 시원한 바람을 즐겼습니다.'
    UNION ALL SELECT 19, '여행 가방 꾸리기', '필요한 물건만 넣으니 가방이 가벼웠습니다.'
    UNION ALL SELECT 20, '방학의 비 오는 날', '비가 와서 숙소에서 여행 지도를 살펴보았습니다.'
    UNION ALL SELECT 21, '대전 빵집 탐방', '대전에서 유명한 빵집 몇 곳을 찾아갔습니다.'
    UNION ALL SELECT 22, '여행지 엽서', '마음에 드는 풍경을 엽서로 남겼습니다.'
    UNION ALL SELECT 23, '방학 오후의 휴식', '더운 오후에는 잠시 쉬고 저녁에 산책했습니다.'
    UNION ALL SELECT 24, '여수 밤바다', '여수의 밤바다는 생각보다 더 반짝였습니다.'
    UNION ALL SELECT 25, '여행 앱 활용법', '지도와 교통 앱을 함께 쓰니 길 찾기가 쉬웠습니다.'
    UNION ALL SELECT 26, '방학 친구 모임', '친구들과 다음 여행지를 정하며 즐거운 시간을 보냈습니다.'
    UNION ALL SELECT 27, '춘천 호수 풍경', '호수 옆 벤치에 앉아 조용히 풍경을 보았습니다.'
    UNION ALL SELECT 28, '여행 중 아침 식사', '숙소 근처 빵집에서 간단히 아침을 먹었습니다.'
    UNION ALL SELECT 29, '방학 공부 시간', '여행이 없는 날에는 오전에 공부를 마쳤습니다.'
    UNION ALL SELECT 30, '인천 차이나타운', '골목마다 다른 색의 건물을 보는 재미가 있었습니다.'
    UNION ALL SELECT 31, '여행 일기 시작', '짧게라도 하루의 기억을 적어 두기로 했습니다.'
    UNION ALL SELECT 32, '방학 저녁 산책', '해가 진 뒤 동네를 걷는 시간이 여유로웠습니다.'
    UNION ALL SELECT 33, '담양 대나무숲', '대나무숲의 그늘 덕분에 시원하게 걸었습니다.'
    UNION ALL SELECT 34, '여행 간식 추천', '물과 과일을 챙기면 이동 중에 유용했습니다.'
    UNION ALL SELECT 35, '방학 카페 공부', '조용한 카페에서 여행 계획도 함께 세웠습니다.'
    UNION ALL SELECT 36, '통영 항구', '항구 주변에서 바다 냄새를 맡으며 걸었습니다.'
    UNION ALL SELECT 37, '여행 경비 기록', '작은 지출도 메모하니 예산 관리가 쉬웠습니다.'
    UNION ALL SELECT 38, '방학 요리 연습', '여행지에서 먹은 음식을 집에서 따라 만들어 봤습니다.'
    UNION ALL SELECT 39, '제주 오름 걷기', '낮은 오름을 올라가니 넓은 풍경이 펼쳐졌습니다.'
    UNION ALL SELECT 40, '여행 전 날씨 확인', '비 예보를 확인하고 우산을 챙겼습니다.'
    UNION ALL SELECT 41, '방학의 느린 아침', '알람 없이 일어나 천천히 하루를 시작했습니다.'
    UNION ALL SELECT 42, '군산 근대 거리', '오래된 건물을 보며 천천히 사진을 찍었습니다.'
    UNION ALL SELECT 43, '여행지 버스 타기', '지역 버스를 타니 동네 분위기를 더 느낄 수 있었습니다.'
    UNION ALL SELECT 44, '방학 방 정리', '여행 전 방을 정리하니 마음도 가벼워졌습니다.'
    UNION ALL SELECT 45, '포항 바다 드라이브', '해안 도로를 따라 달리며 바다를 보았습니다.'
    UNION ALL SELECT 46, '여행 중 책 읽기', '이동 시간에 읽은 책이 좋은 동반자가 되었습니다.'
    UNION ALL SELECT 47, '방학의 별 보기', '도시를 벗어나니 밤하늘의 별이 잘 보였습니다.'
    UNION ALL SELECT 48, '안동 하회마을', '고즈넉한 마을 길을 걸으며 여유를 느꼈습니다.'
    UNION ALL SELECT 49, '여행지 기념품', '작고 실용적인 기념품 하나를 골랐습니다.'
    UNION ALL SELECT 50, '방학 중간 점검', '남은 방학 계획을 다시 정리해 보았습니다.'
    UNION ALL SELECT 51, '수원 화성 산책', '성곽 길을 따라 걸으며 도시 풍경을 보았습니다.'
    UNION ALL SELECT 52, '여행 친구와 역할 분담', '숙소와 식당을 나누어 찾으니 준비가 빨랐습니다.'
    UNION ALL SELECT 53, '방학 음악 목록', '여행길에 들을 음악을 미리 골랐습니다.'
    UNION ALL SELECT 54, '태안 해변', '한적한 해변에서 파도 소리를 오래 들었습니다.'
    UNION ALL SELECT 55, '여행 사진 한 장', '가장 마음에 드는 사진을 배경화면으로 바꿨습니다.'
    UNION ALL SELECT 56, '방학의 아이스크림', '더운 날에는 여행지에서 아이스크림을 먹었습니다.'
    UNION ALL SELECT 57, '청주 골목 여행', '작은 골목의 서점과 카페를 찾아다녔습니다.'
    UNION ALL SELECT 58, '여행 후 빨래', '돌아온 날 바로 짐을 정리하니 편했습니다.'
    UNION ALL SELECT 59, '방학 일찍 잠들기', '다음 날 여행을 위해 평소보다 일찍 쉬었습니다.'
    UNION ALL SELECT 60, '울산 대왕암', '바위와 바다가 어우러진 풍경이 인상적이었습니다.'
    UNION ALL SELECT 61, '여행 일정 비우기', '일정을 너무 채우지 않으니 마음이 편했습니다.'
    UNION ALL SELECT 62, '방학 새벽 공기', '새벽 산책을 하니 공기가 맑고 조용했습니다.'
    UNION ALL SELECT 63, '보령 해수욕장', '모래사장을 걸으며 여름 분위기를 즐겼습니다.'
    UNION ALL SELECT 64, '여행지 아침 시장', '아침 시장에서 신선한 과일을 샀습니다.'
    UNION ALL SELECT 65, '방학 편지 쓰기', '여행 중 만난 친구에게 짧은 편지를 썼습니다.'
    UNION ALL SELECT 66, '목포 항구 풍경', '항구 근처에서 해가 지는 모습을 보았습니다.'
    UNION ALL SELECT 67, '여행용 신발', '많이 걷는 날에는 편한 운동화가 가장 좋았습니다.'
    UNION ALL SELECT 68, '방학의 낮잠', '더운 오후에 잠시 쉬고 나니 다시 힘이 났습니다.'
    UNION ALL SELECT 69, '파주 책방 여행', '책방에서 여행 안내서를 천천히 읽었습니다.'
    UNION ALL SELECT 70, '여행지 예약 확인', '출발 전 교통과 숙소 예약을 다시 확인했습니다.'
    UNION ALL SELECT 71, '방학 운동화 세탁', '여행 후 더러워진 운동화를 깨끗이 빨았습니다.'
    UNION ALL SELECT 72, '서산 간월암', '바닷길이 열리는 시간을 맞춰 방문했습니다.'
    UNION ALL SELECT 73, '여행 중 길 잃기', '길을 조금 돌아가며 예상치 못한 풍경을 만났습니다.'
    UNION ALL SELECT 74, '방학 버킷리스트', '가보고 싶은 국내 여행지를 열 개 적었습니다.'
    UNION ALL SELECT 75, '공주 공산성', '성 위에서 내려다본 강 풍경이 아름다웠습니다.'
    UNION ALL SELECT 76, '여행 지도 표시', '다녀온 장소를 지도에 표시하며 추억을 남겼습니다.'
    UNION ALL SELECT 77, '방학 저녁 요리', '여행지에서 배운 간단한 요리를 만들었습니다.'
    UNION ALL SELECT 78, '진주성 방문', '성 안을 천천히 둘러보며 역사 이야기를 읽었습니다.'
    UNION ALL SELECT 79, '여행 중 충전기', '보조 배터리를 챙겨 휴대폰 걱정을 덜었습니다.'
    UNION ALL SELECT 80, '방학 아침 시장', '일찍 일어나 시장에서 따뜻한 국밥을 먹었습니다.'
    UNION ALL SELECT 81, '부여 궁남지', '연못 주변을 걸으며 조용한 시간을 보냈습니다.'
    UNION ALL SELECT 82, '여행지의 일몰', '하루 마지막에 본 일몰이 가장 기억에 남습니다.'
    UNION ALL SELECT 83, '방학 계획표', '휴식과 여행 날짜를 균형 있게 배치했습니다.'
    UNION ALL SELECT 84, '남원 광한루', '정원을 둘러보며 시원한 바람을 맞았습니다.'
    UNION ALL SELECT 85, '여행 전 짐 점검', '출발 전 필요한 물건을 한 번 더 확인했습니다.'
    UNION ALL SELECT 86, '방학 친구와 사진', '친구들과 찍은 사진을 함께 나누었습니다.'
    UNION ALL SELECT 87, '고창 고인돌', '넓은 들판에서 오래된 유적을 보았습니다.'
    UNION ALL SELECT 88, '여행 후 감사', '함께한 사람들에게 사진과 함께 인사를 전했습니다.'
    UNION ALL SELECT 89, '방학의 마지막 주', '남은 시간을 아끼며 가까운 곳을 더 둘러봤습니다.'
    UNION ALL SELECT 90, '영월 별마로 천문대', '밤하늘을 보며 여행의 마지막을 장식했습니다.'
    UNION ALL SELECT 91, '여행 후 일상 복귀', '사진을 보며 다음 여행을 기대했습니다.'
    UNION ALL SELECT 92, '방학 아침 커피', '여행 전 조용히 커피를 마시며 일정을 확인했습니다.'
    UNION ALL SELECT 93, '제천 호수 여행', '호수 주변 산책로에서 바람을 느꼈습니다.'
    UNION ALL SELECT 94, '여행 가계부', '교통비와 식비를 적으며 여행을 정리했습니다.'
    UNION ALL SELECT 95, '방학 마무리 청소', '여행 가방을 비우고 방을 정돈했습니다.'
    UNION ALL SELECT 96, '양양 서핑 구경', '파도를 타는 사람들을 보며 해변을 걸었습니다.'
    UNION ALL SELECT 97, '여행의 좋은 순간', '예상하지 못한 작은 풍경이 가장 좋았습니다.'
    UNION ALL SELECT 98, '방학 다음 계획', '다음 방학에도 새로운 도시를 찾아가고 싶습니다.'
    UNION ALL SELECT 99, '여행을 마치며', '이번 방학 여행 덕분에 즐거운 추억이 많아졌습니다.'
) AS item
WHERE member.username = 'vacationer';
